import streamlit
streamlit.title('Hello World ! First Streamlit App')
streamlit.header('Application Menu')
streamlit.text('Learn Snowflake')
streamlit.text('Create GitHub Account')
streamlit.text('Create Streamlit Account through GitHub')
streamlit.text('Provide Access to Streamlit')
streamlit.header('Breakfast Menu')
streamlit.text('🥣 Omega3 and Oatmeal')
streamlit.text('🥗 Kale, Spinach and Rocket Smoothie')
streamit.text('🥑🍞 Avocado Toast')
